# Generated by Django 2.2.18 on 2021-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariants',
            name='Lead_post',
            field=models.CharField(blank=True, help_text='Должность', max_length=255, null=True, verbose_name='Lead post '),
        ),
    ]
