# Generated by Django 2.2.18 on 2021-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_variants', '0002_appvariants_lead_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariants',
            name='footer_title',
            field=models.TextField(blank=True, help_text='title info, only char, not html tag!', null=True, verbose_name='footer title'),
        ),
    ]
