# Generated by Django 2.2.18 on 2021-03-04 06:28

from django.db import migrations, models
import project_map.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('apps_variants', '0003_appvariants_footer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariants',
            name='mobile_logo',
            field=models.FileField(blank=True, help_text='the mobile logo of the website', null=True, upload_to=project_map.utils.media.get_media_path, verbose_name='Mobile site logo'),
        ),
    ]
