# Generated by Django 2.2.18 on 2021-02-24 08:27

import any_imagefield.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Category')),
                ('color', models.CharField(blank=True, max_length=14, null=True, verbose_name='Цвет')),
                ('marker_im', any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Rayon')),
                ('adress', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adress')),
                ('coords', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Coordinates')),
            ],
            options={
                'verbose_name': 'Rayon',
                'verbose_name_plural': 'Rayones',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Project title')),
                ('adress', models.CharField(max_length=1000, verbose_name='Adress')),
                ('marker_im', any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('marker', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Координаты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.Category')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.Rayon')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
