# Generated by Django 2.2.18 on 2021-03-02 11:02

import any_imagefield.models.fields
from django.db import migrations, models
import django.db.models.deletion
import project_map.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0004_auto_20210301_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='RayonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_icon', any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to=project_map.utils.media.get_media_path, verbose_name='Image')),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Наименование категории')),
                ('objects_count', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Количество объектов')),
                ('investments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Объем инвестиций')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.Rayon')),
            ],
        ),
        migrations.CreateModel(
            name='RayonSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_icon', any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to=project_map.utils.media.get_media_path, verbose_name='Image')),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Наименование подкатегории')),
                ('objects_count', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Количество объектов')),
                ('investments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Объем инвестиций')),
                ('rayon_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.RayonCategory')),
            ],
        ),
    ]
