# Generated by Django 2.2.18 on 2021-03-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0006_rayon_gerb_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_map.Rayon', verbose_name='Rayon'),
        ),
        migrations.AlterField(
            model_name='rayoncategory',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayon', to='project_map.Rayon'),
        ),
        migrations.AlterField(
            model_name='rayonsubcategory',
            name='rayon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayon_category', to='project_map.RayonCategory'),
        ),
    ]
