# Generated by Django 2.2.18 on 2021-03-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0007_auto_20210302_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rayoncategory',
            name='category_icon',
        ),
        migrations.RemoveField(
            model_name='rayonsubcategory',
            name='category_icon',
        ),
    ]
