# Generated by Django 2.2.18 on 2021-03-03 08:01

import any_imagefield.models.fields
from django.db import migrations
import project_map.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0008_auto_20210302_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to=project_map.utils.media.get_media_path, verbose_name='Image'),
        ),
    ]
