# Generated by Django 2.2.18 on 2021-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0010_auto_20210303_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='financi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем финансирования'),
        ),
    ]
