# Generated by Django 2.2.18 on 2021-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0012_auto_20210303_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='marker',
            field=models.CharField(default=1, help_text='Координаты должны быть типа [50.388111,36.880136], обязательно в квадратных скобках и без пробелов', max_length=10000, verbose_name='Координаты'),
            preserve_default=False,
        ),
    ]
