# Generated by Django 2.2.18 on 2021-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0013_auto_20210303_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='full_investments',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Общий объем финансирования'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='full_objects_count',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Всего объектов'),
        ),
    ]
