# Generated by Django 2.2.18 on 2021-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0014_auto_20210304_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Позиция в сортировке'),
        ),
    ]
