# Generated by Django 2.2.18 on 2021-03-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0016_projectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project_map.Project', verbose_name='Изображение'),
        ),
    ]
