# Generated by Django 2.2.18 on 2021-03-10 12:33

import any_imagefield.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0018_auto_20210305_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='infografika_im',
            field=any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to='', verbose_name='Инфографика'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='mobile_infografika_im',
            field=any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to='', verbose_name='Инфографика для мобильной версии'),
        ),
    ]
