# Generated by Django 2.2.18 on 2021-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0019_auto_20210310_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
