# Generated by Django 2.2.18 on 2021-07-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0022_auto_20210720_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completephoto',
            options={'verbose_name': 'Фото выполненного объекта', 'verbose_name_plural': 'Фотографии выполненного объекта'},
        ),
    ]
