# Generated by Django 2.2.18 on 2021-08-21 10:04

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project_map', '0023_auto_20210720_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='For use into URL', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='decription')),
                ('active', models.BooleanField(default=False, help_text='If this flag disable the entity not show on site', verbose_name='active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_map.BaseRubric', verbose_name='parent')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_project_map.baserubric_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Base Rubric',
                'verbose_name_plural': 'Base Rubrics',
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('baserubric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_map.BaseRubric')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
            },
            bases=('project_map.baserubric',),
        ),
    ]
