# Generated by Django 2.2.18 on 2021-08-21 10:08

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_map', '0024_baserubric_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rubrics',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='related_entities', to='project_map.BaseRubric', verbose_name='rubrics'),
        ),
    ]
